version: '3.5'

services:
  postgres:
    image: postgres:11-alpine
    container_name: PostgresTest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=anypass
      - POSTGRES_DB=crowd
#      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  similarity:
    image: lazarmr100/ron_anivission_home_assignment:latest
    container_name: similarityContainer
    ports:
      - "80:8080"
      - "8090:8090"
